export const FAKE_DATA = [
  {
    ref: 'P0001',
    jobTitle: 'NetSuite Admin',
    firstName: 'John',
    lastName: 'Smith',
    client: 'Mac Business',
    rate: '32',
    supervisor: 'Marc Jones',
    supervisorEmail: 'mjones22@gmail.com',
    billingEmail: 'sample343@aol.com',
  },
  {
    ref: 'P0002',
    jobTitle: 'NetSuite Consultant',
    firstName: 'Al',
    lastName: 'Aagrav',
    client: 'Centium',
    rate: '43.23',
    supervisor: 'Rick Grimes',
    supervisorEmail: 'rgrimes112@gmail.com',
    billingEmail: 'example2123@yahoo.com',
  },
  {
    ref: 'P0003',
    jobTitle: 'NetSuite Senior Consultant',
    firstName: 'Rick ',
    lastName: 'Owens',
    client: 'Roles & Co',
    rate: '20.50',
    supervisor: 'Marc Jones',
    supervisorEmail: 'mjones22@gmail.com',
    billingEmail: 'sample343@aol.com',
  },
  {
    ref: 'P0004',
    jobTitle: 'NetSuite Support',
    firstName: 'Bob',
    lastName: 'Peterson',
    client: 'Scorpion Athletics',
    rate: '25',
    supervisor: 'Rick Grimes',
    supervisorEmail: 'rgrimes112@gmail.com',
    billingEmail: 'example2123@yahoo.com',
  },
  {
    ref: 'P0005',
    jobTitle: 'NetSuite SCA Project',
    firstName: 'Ryan',
    lastName: 'Johnson',
    client: 'MaxLyfe',
    rate: '50',
    supervisor: 'Marc Jones',
    supervisorEmail: 'mjones22@gmail.com',
    billingEmail: 'sample343@aol.com',
  },
];
